version: '3'
services:
  producer:
    depends_on:
      - kafka
    build:
      context: ./transporter
    networks:
      - eurobonds-liquidity-network
    volumes:
      - delta:/storage
      - shara:/shara
  kafka:
    image: spotify/kafka
    networks:
      - eurobonds-liquidity-network
    volumes:
      - delta:/storage
      - shara:/shara
networks:
  eurobonds-liquidity-network:
    external:
      name: eurobonds-liquidity-network

volumes:
  delta:
  shara: